### ISSUE TITLE
1.23.0 causes nxdomain error

### ISSUE THREAD

**Issue by Kalaww** [benoitc/hackney#764]
I have upgraded hackney from 1.20 to 1.23 and I noticed some of my http requests are failing with `nxdomain` in my gitlab ci job. I am using hackney through tesla lib.

### Trace
```
[hackney trace 80 <0.798.0> 2025:02:27 10:33:43 4446] request 
   Content: [{module,hackney},
             {line,313},
             {method,get},
             {url,{hackney_url,hackney_tcp,http,<<"rabbitmq:15672">>,
                               <<"/api/vhosts">>,<<"/api/vhosts">>,<<>>,<<>>,
                               "rabbitmq",15672,<<>>,<<>>}},
             {headers,[{<<"authorization">>,<<"Basic Z3Vlc3Q6Z3Vlc3Q=">>},
                       {<<"content-type">>,<<"application/json">>}]},
             {body,[]},
             {options,[{pool,default}]}]
[hackney trace 60 <0.798.0> 2025:02:27 10:33:43 4447] no proxy env setup, request without proxy 
   Content: [{module,hackney},{line,695}]
[hackney trace 60 <0.798.0> 2025:02:27 10:33:43 4448] connect 
   Content: [{module,hackney_connect},
             {line,32},
             {transport,hackney_tcp},
             {host,"rabbitmq"},
             {port,15672},
             {dynamic,true}]
[hackney trace 80 <0.798.0> 2025:02:27 10:33:43 4450] no socket in the pool 
   Content: [{module,hackney_pool},{line,88},{pool,default}]
[hackney trace 60 <0.798.0> 2025:02:27 10:33:43 4452] happy eyeballs, try to connect using IPv6 
   Content: [{module,hackney_happy},
             {line,32},
             {hostname,"rabbitmq"},
             {port,15672},
             {timeout,8000}]
[hackney trace 80 <0.798.0> 2025:02:27 10:33:43 4464] connect error 
   Content: [{module,hackney_pool},
             {line,108},
             {pool,default},
             {error,{error,nxdomain}}]
[hackney trace 80 <0.798.0> 2025:02:27 10:33:43 4464] connect error 
   Content: [{module,hackney_connect},{line,238}]
```

**Comment by Kalaww** [comment]
I have tested with 1.22.0 and same issue.
Also, when I run my tests locally using `localhost` instead of `rabbitmq` for the hostname it works fine.

**Comment by Lgdev07** [comment]
Hi, we also have the same problem for v1.22 / v1.23

**Comment by benoitc** [comment]
well how can I reproduce? How do you define the ip attached to this host name?  on which os?

**Comment by Kalaww** [comment]
I am sorry for the lazy description. I managed to reproduced it in a docker compose. Create a file `test.ex` and a docker compose file with the content you can find below and run this `docker compose up --build | grep elixir`.
If you change the hackney version to 1.20.1, the issue is not there.
Also I am using elixir 1.18 and otp 26.

**test.ex**
```elixir
Mix.install([{:hackney, "== 1.23.0"}])

:hackney.request(
  :get,
  "http://rabbitmq:15672/api/vhosts",
  [{"Authorization", "Basic Z3Vlc3Q6Z3Vlc3Q="}],
  <<>>,
  []
)
|> IO.inspect()
```


**docker-compose.yaml**
```yaml
services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  elixir:
    image: elixir:1.18-otp-26-alpine
    depends_on:
      - rabbitmq
    command: sh -c "elixir /test.ex"
    volumes:
      - ./test.ex:/test.ex
```
